// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.3
// - protoc             v4.24.4
// source: api/manager/department/manager_department_service.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationDepartmentCreateDepartment = "/manager.api.manager.department.v1.Department/CreateDepartment"
const OperationDepartmentDeleteDepartment = "/manager.api.manager.department.v1.Department/DeleteDepartment"
const OperationDepartmentGetDepartment = "/manager.api.manager.department.v1.Department/GetDepartment"
const OperationDepartmentListDepartment = "/manager.api.manager.department.v1.Department/ListDepartment"
const OperationDepartmentUpdateDepartment = "/manager.api.manager.department.v1.Department/UpdateDepartment"

type DepartmentHTTPServer interface {
	// CreateDepartment CreateDepartment 创建部门信息
	CreateDepartment(context.Context, *CreateDepartmentRequest) (*CreateDepartmentReply, error)
	// DeleteDepartment DeleteDepartment 删除部门信息
	DeleteDepartment(context.Context, *DeleteDepartmentRequest) (*DeleteDepartmentReply, error)
	// GetDepartment GetDepartment 获取指定的部门信息
	GetDepartment(context.Context, *GetDepartmentRequest) (*GetDepartmentReply, error)
	// ListDepartment ListDepartment 获取部门信息列表
	ListDepartment(context.Context, *ListDepartmentRequest) (*ListDepartmentReply, error)
	// UpdateDepartment UpdateDepartment 更新部门信息
	UpdateDepartment(context.Context, *UpdateDepartmentRequest) (*UpdateDepartmentReply, error)
}

func RegisterDepartmentHTTPServer(s *http.Server, srv DepartmentHTTPServer) {
	r := s.Route("/")
	r.GET("/manager/api/v1/departments", _Department_ListDepartment0_HTTP_Handler(srv))
	r.POST("/manager/api/v1/department", _Department_CreateDepartment0_HTTP_Handler(srv))
	r.PUT("/manager/api/v1/department", _Department_UpdateDepartment0_HTTP_Handler(srv))
	r.DELETE("/manager/api/v1/department", _Department_DeleteDepartment0_HTTP_Handler(srv))
	r.GET("/manager/api/v1/department", _Department_GetDepartment0_HTTP_Handler(srv))
}

func _Department_ListDepartment0_HTTP_Handler(srv DepartmentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListDepartmentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDepartmentListDepartment)
		h := ctx.Middleware(func(ctx context.Context, req any) (any, error) {
			return srv.ListDepartment(ctx, req.(*ListDepartmentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListDepartmentReply)
		return ctx.Result(200, reply)
	}
}

func _Department_CreateDepartment0_HTTP_Handler(srv DepartmentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateDepartmentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDepartmentCreateDepartment)
		h := ctx.Middleware(func(ctx context.Context, req any) (any, error) {
			return srv.CreateDepartment(ctx, req.(*CreateDepartmentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateDepartmentReply)
		return ctx.Result(200, reply)
	}
}

func _Department_UpdateDepartment0_HTTP_Handler(srv DepartmentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateDepartmentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDepartmentUpdateDepartment)
		h := ctx.Middleware(func(ctx context.Context, req any) (any, error) {
			return srv.UpdateDepartment(ctx, req.(*UpdateDepartmentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateDepartmentReply)
		return ctx.Result(200, reply)
	}
}

func _Department_DeleteDepartment0_HTTP_Handler(srv DepartmentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteDepartmentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDepartmentDeleteDepartment)
		h := ctx.Middleware(func(ctx context.Context, req any) (any, error) {
			return srv.DeleteDepartment(ctx, req.(*DeleteDepartmentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteDepartmentReply)
		return ctx.Result(200, reply)
	}
}

func _Department_GetDepartment0_HTTP_Handler(srv DepartmentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDepartmentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDepartmentGetDepartment)
		h := ctx.Middleware(func(ctx context.Context, req any) (any, error) {
			return srv.GetDepartment(ctx, req.(*GetDepartmentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetDepartmentReply)
		return ctx.Result(200, reply)
	}
}

type DepartmentHTTPClient interface {
	CreateDepartment(ctx context.Context, req *CreateDepartmentRequest, opts ...http.CallOption) (rsp *CreateDepartmentReply, err error)
	DeleteDepartment(ctx context.Context, req *DeleteDepartmentRequest, opts ...http.CallOption) (rsp *DeleteDepartmentReply, err error)
	GetDepartment(ctx context.Context, req *GetDepartmentRequest, opts ...http.CallOption) (rsp *GetDepartmentReply, err error)
	ListDepartment(ctx context.Context, req *ListDepartmentRequest, opts ...http.CallOption) (rsp *ListDepartmentReply, err error)
	UpdateDepartment(ctx context.Context, req *UpdateDepartmentRequest, opts ...http.CallOption) (rsp *UpdateDepartmentReply, err error)
}

type DepartmentHTTPClientImpl struct {
	cc *http.Client
}

func NewDepartmentHTTPClient(client *http.Client) DepartmentHTTPClient {
	return &DepartmentHTTPClientImpl{client}
}

func (c *DepartmentHTTPClientImpl) CreateDepartment(ctx context.Context, in *CreateDepartmentRequest, opts ...http.CallOption) (*CreateDepartmentReply, error) {
	var out CreateDepartmentReply
	pattern := "/manager/api/v1/department"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDepartmentCreateDepartment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *DepartmentHTTPClientImpl) DeleteDepartment(ctx context.Context, in *DeleteDepartmentRequest, opts ...http.CallOption) (*DeleteDepartmentReply, error) {
	var out DeleteDepartmentReply
	pattern := "/manager/api/v1/department"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDepartmentDeleteDepartment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *DepartmentHTTPClientImpl) GetDepartment(ctx context.Context, in *GetDepartmentRequest, opts ...http.CallOption) (*GetDepartmentReply, error) {
	var out GetDepartmentReply
	pattern := "/manager/api/v1/department"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDepartmentGetDepartment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *DepartmentHTTPClientImpl) ListDepartment(ctx context.Context, in *ListDepartmentRequest, opts ...http.CallOption) (*ListDepartmentReply, error) {
	var out ListDepartmentReply
	pattern := "/manager/api/v1/departments"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDepartmentListDepartment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *DepartmentHTTPClientImpl) UpdateDepartment(ctx context.Context, in *UpdateDepartmentRequest, opts ...http.CallOption) (*UpdateDepartmentReply, error) {
	var out UpdateDepartmentReply
	pattern := "/manager/api/v1/department"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDepartmentUpdateDepartment))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
