// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.24.4
// source: api/manager/dictionary/manager_dictionary_value.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDictionaryValuesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keywords []string `protobuf:"bytes,1,rep,name=keywords,proto3" json:"keywords,omitempty"`
}

func (x *GetDictionaryValuesRequest) Reset() {
	*x = GetDictionaryValuesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDictionaryValuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDictionaryValuesRequest) ProtoMessage() {}

func (x *GetDictionaryValuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDictionaryValuesRequest.ProtoReflect.Descriptor instead.
func (*GetDictionaryValuesRequest) Descriptor() ([]byte, []int) {
	return file_api_manager_dictionary_manager_dictionary_value_proto_rawDescGZIP(), []int{0}
}

func (x *GetDictionaryValuesRequest) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

type GetDictionaryValuesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dict map[string]*GetDictionaryValuesReply_Value `protobuf:"bytes,1,rep,name=dict,proto3" json:"dict,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetDictionaryValuesReply) Reset() {
	*x = GetDictionaryValuesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDictionaryValuesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDictionaryValuesReply) ProtoMessage() {}

func (x *GetDictionaryValuesReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDictionaryValuesReply.ProtoReflect.Descriptor instead.
func (*GetDictionaryValuesReply) Descriptor() ([]byte, []int) {
	return file_api_manager_dictionary_manager_dictionary_value_proto_rawDescGZIP(), []int{1}
}

func (x *GetDictionaryValuesReply) GetDict() map[string]*GetDictionaryValuesReply_Value {
	if x != nil {
		return x.Dict
	}
	return nil
}

type ListDictionaryValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page         uint32  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize     uint32  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Order        *string `protobuf:"bytes,3,opt,name=order,proto3,oneof" json:"order,omitempty"`
	OrderBy      *string `protobuf:"bytes,4,opt,name=orderBy,proto3,oneof" json:"orderBy,omitempty"`
	DictionaryId *uint32 `protobuf:"varint,5,opt,name=dictionaryId,proto3,oneof" json:"dictionaryId,omitempty"`
	Label        *string `protobuf:"bytes,6,opt,name=label,proto3,oneof" json:"label,omitempty"`
	Value        *string `protobuf:"bytes,7,opt,name=value,proto3,oneof" json:"value,omitempty"`
	Status       *bool   `protobuf:"varint,8,opt,name=status,proto3,oneof" json:"status,omitempty"`
}

func (x *ListDictionaryValueRequest) Reset() {
	*x = ListDictionaryValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDictionaryValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDictionaryValueRequest) ProtoMessage() {}

func (x *ListDictionaryValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDictionaryValueRequest.ProtoReflect.Descriptor instead.
func (*ListDictionaryValueRequest) Descriptor() ([]byte, []int) {
	return file_api_manager_dictionary_manager_dictionary_value_proto_rawDescGZIP(), []int{2}
}

func (x *ListDictionaryValueRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDictionaryValueRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDictionaryValueRequest) GetOrder() string {
	if x != nil && x.Order != nil {
		return *x.Order
	}
	return ""
}

func (x *ListDictionaryValueRequest) GetOrderBy() string {
	if x != nil && x.OrderBy != nil {
		return *x.OrderBy
	}
	return ""
}

func (x *ListDictionaryValueRequest) GetDictionaryId() uint32 {
	if x != nil && x.DictionaryId != nil {
		return *x.DictionaryId
	}
	return 0
}

func (x *ListDictionaryValueRequest) GetLabel() string {
	if x != nil && x.Label != nil {
		return *x.Label
	}
	return ""
}

func (x *ListDictionaryValueRequest) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *ListDictionaryValueRequest) GetStatus() bool {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return false
}

type ListDictionaryValueReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total uint32                                      `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*ListDictionaryValueReply_DictionaryValue `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ListDictionaryValueReply) Reset() {
	*x = ListDictionaryValueReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDictionaryValueReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDictionaryValueReply) ProtoMessage() {}

func (x *ListDictionaryValueReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDictionaryValueReply.ProtoReflect.Descriptor instead.
func (*ListDictionaryValueReply) Descriptor() ([]byte, []int) {
	return file_api_manager_dictionary_manager_dictionary_value_proto_rawDescGZIP(), []int{3}
}

func (x *ListDictionaryValueReply) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListDictionaryValueReply) GetList() []*ListDictionaryValueReply_DictionaryValue {
	if x != nil {
		return x.List
	}
	return nil
}

type CreateDictionaryValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DictionaryId uint32  `protobuf:"varint,1,opt,name=dictionaryId,proto3" json:"dictionaryId,omitempty"`
	Label        string  `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Value        string  `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Status       *bool   `protobuf:"varint,4,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Weight       *int32  `protobuf:"varint,5,opt,name=weight,proto3,oneof" json:"weight,omitempty"`
	Type         *string `protobuf:"bytes,6,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Extra        *string `protobuf:"bytes,7,opt,name=extra,proto3,oneof" json:"extra,omitempty"`
	Description  *string `protobuf:"bytes,8,opt,name=description,proto3,oneof" json:"description,omitempty"`
}

func (x *CreateDictionaryValueRequest) Reset() {
	*x = CreateDictionaryValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDictionaryValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDictionaryValueRequest) ProtoMessage() {}

func (x *CreateDictionaryValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDictionaryValueRequest.ProtoReflect.Descriptor instead.
func (*CreateDictionaryValueRequest) Descriptor() ([]byte, []int) {
	return file_api_manager_dictionary_manager_dictionary_value_proto_rawDescGZIP(), []int{4}
}

func (x *CreateDictionaryValueRequest) GetDictionaryId() uint32 {
	if x != nil {
		return x.DictionaryId
	}
	return 0
}

func (x *CreateDictionaryValueRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CreateDictionaryValueRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CreateDictionaryValueRequest) GetStatus() bool {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return false
}

func (x *CreateDictionaryValueRequest) GetWeight() int32 {
	if x != nil && x.Weight != nil {
		return *x.Weight
	}
	return 0
}

func (x *CreateDictionaryValueRequest) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *CreateDictionaryValueRequest) GetExtra() string {
	if x != nil && x.Extra != nil {
		return *x.Extra
	}
	return ""
}

func (x *CreateDictionaryValueRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type CreateDictionaryValueReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateDictionaryValueReply) Reset() {
	*x = CreateDictionaryValueReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDictionaryValueReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDictionaryValueReply) ProtoMessage() {}

func (x *CreateDictionaryValueReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDictionaryValueReply.ProtoReflect.Descriptor instead.
func (*CreateDictionaryValueReply) Descriptor() ([]byte, []int) {
	return file_api_manager_dictionary_manager_dictionary_value_proto_rawDescGZIP(), []int{5}
}

func (x *CreateDictionaryValueReply) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateDictionaryValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DictionaryId uint32  `protobuf:"varint,2,opt,name=dictionaryId,proto3" json:"dictionaryId,omitempty"`
	Label        string  `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Value        string  `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Weight       *int32  `protobuf:"varint,5,opt,name=weight,proto3,oneof" json:"weight,omitempty"`
	Type         *string `protobuf:"bytes,6,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Extra        *string `protobuf:"bytes,7,opt,name=extra,proto3,oneof" json:"extra,omitempty"`
	Description  *string `protobuf:"bytes,8,opt,name=description,proto3,oneof" json:"description,omitempty"`
}

func (x *UpdateDictionaryValueRequest) Reset() {
	*x = UpdateDictionaryValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDictionaryValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDictionaryValueRequest) ProtoMessage() {}

func (x *UpdateDictionaryValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDictionaryValueRequest.ProtoReflect.Descriptor instead.
func (*UpdateDictionaryValueRequest) Descriptor() ([]byte, []int) {
	return file_api_manager_dictionary_manager_dictionary_value_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDictionaryValueRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDictionaryValueRequest) GetDictionaryId() uint32 {
	if x != nil {
		return x.DictionaryId
	}
	return 0
}

func (x *UpdateDictionaryValueRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *UpdateDictionaryValueRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *UpdateDictionaryValueRequest) GetWeight() int32 {
	if x != nil && x.Weight != nil {
		return *x.Weight
	}
	return 0
}

func (x *UpdateDictionaryValueRequest) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *UpdateDictionaryValueRequest) GetExtra() string {
	if x != nil && x.Extra != nil {
		return *x.Extra
	}
	return ""
}

func (x *UpdateDictionaryValueRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type UpdateDictionaryValueReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateDictionaryValueReply) Reset() {
	*x = UpdateDictionaryValueReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDictionaryValueReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDictionaryValueReply) ProtoMessage() {}

func (x *UpdateDictionaryValueReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDictionaryValueReply.ProtoReflect.Descriptor instead.
func (*UpdateDictionaryValueReply) Descriptor() ([]byte, []int) {
	return file_api_manager_dictionary_manager_dictionary_value_proto_rawDescGZIP(), []int{7}
}

type UpdateDictionaryValueStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status bool   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *UpdateDictionaryValueStatusRequest) Reset() {
	*x = UpdateDictionaryValueStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDictionaryValueStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDictionaryValueStatusRequest) ProtoMessage() {}

func (x *UpdateDictionaryValueStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDictionaryValueStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateDictionaryValueStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_manager_dictionary_manager_dictionary_value_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateDictionaryValueStatusRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDictionaryValueStatusRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type UpdateDictionaryValueStatusReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateDictionaryValueStatusReply) Reset() {
	*x = UpdateDictionaryValueStatusReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDictionaryValueStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDictionaryValueStatusReply) ProtoMessage() {}

func (x *UpdateDictionaryValueStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDictionaryValueStatusReply.ProtoReflect.Descriptor instead.
func (*UpdateDictionaryValueStatusReply) Descriptor() ([]byte, []int) {
	return file_api_manager_dictionary_manager_dictionary_value_proto_rawDescGZIP(), []int{9}
}

type DeleteDictionaryValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteDictionaryValueRequest) Reset() {
	*x = DeleteDictionaryValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDictionaryValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDictionaryValueRequest) ProtoMessage() {}

func (x *DeleteDictionaryValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDictionaryValueRequest.ProtoReflect.Descriptor instead.
func (*DeleteDictionaryValueRequest) Descriptor() ([]byte, []int) {
	return file_api_manager_dictionary_manager_dictionary_value_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteDictionaryValueRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteDictionaryValueReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteDictionaryValueReply) Reset() {
	*x = DeleteDictionaryValueReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDictionaryValueReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDictionaryValueReply) ProtoMessage() {}

func (x *DeleteDictionaryValueReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDictionaryValueReply.ProtoReflect.Descriptor instead.
func (*DeleteDictionaryValueReply) Descriptor() ([]byte, []int) {
	return file_api_manager_dictionary_manager_dictionary_value_proto_rawDescGZIP(), []int{11}
}

type GetDictionaryValuesReply_Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*GetDictionaryValuesReply_Value_Item `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *GetDictionaryValuesReply_Value) Reset() {
	*x = GetDictionaryValuesReply_Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDictionaryValuesReply_Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDictionaryValuesReply_Value) ProtoMessage() {}

func (x *GetDictionaryValuesReply_Value) ProtoReflect() protoreflect.Message {
	mi := &file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDictionaryValuesReply_Value.ProtoReflect.Descriptor instead.
func (*GetDictionaryValuesReply_Value) Descriptor() ([]byte, []int) {
	return file_api_manager_dictionary_manager_dictionary_value_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetDictionaryValuesReply_Value) GetList() []*GetDictionaryValuesReply_Value_Item {
	if x != nil {
		return x.List
	}
	return nil
}

type GetDictionaryValuesReply_Value_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Label       string  `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Value       string  `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Type        *string `protobuf:"bytes,3,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Extra       *string `protobuf:"bytes,4,opt,name=extra,proto3,oneof" json:"extra,omitempty"`
	Description *string `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
}

func (x *GetDictionaryValuesReply_Value_Item) Reset() {
	*x = GetDictionaryValuesReply_Value_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDictionaryValuesReply_Value_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDictionaryValuesReply_Value_Item) ProtoMessage() {}

func (x *GetDictionaryValuesReply_Value_Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDictionaryValuesReply_Value_Item.ProtoReflect.Descriptor instead.
func (*GetDictionaryValuesReply_Value_Item) Descriptor() ([]byte, []int) {
	return file_api_manager_dictionary_manager_dictionary_value_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *GetDictionaryValuesReply_Value_Item) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *GetDictionaryValuesReply_Value_Item) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetDictionaryValuesReply_Value_Item) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *GetDictionaryValuesReply_Value_Item) GetExtra() string {
	if x != nil && x.Extra != nil {
		return *x.Extra
	}
	return ""
}

func (x *GetDictionaryValuesReply_Value_Item) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type ListDictionaryValueReply_DictionaryValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DictionaryId uint32  `protobuf:"varint,2,opt,name=dictionaryId,proto3" json:"dictionaryId,omitempty"`
	Label        string  `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Value        string  `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Status       *bool   `protobuf:"varint,5,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Weight       *int32  `protobuf:"varint,6,opt,name=weight,proto3,oneof" json:"weight,omitempty"`
	Type         *string `protobuf:"bytes,7,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Extra        *string `protobuf:"bytes,8,opt,name=extra,proto3,oneof" json:"extra,omitempty"`
	Description  *string `protobuf:"bytes,9,opt,name=description,proto3,oneof" json:"description,omitempty"`
	CreatedAt    uint32  `protobuf:"varint,10,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt    uint32  `protobuf:"varint,11,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
}

func (x *ListDictionaryValueReply_DictionaryValue) Reset() {
	*x = ListDictionaryValueReply_DictionaryValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDictionaryValueReply_DictionaryValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDictionaryValueReply_DictionaryValue) ProtoMessage() {}

func (x *ListDictionaryValueReply_DictionaryValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDictionaryValueReply_DictionaryValue.ProtoReflect.Descriptor instead.
func (*ListDictionaryValueReply_DictionaryValue) Descriptor() ([]byte, []int) {
	return file_api_manager_dictionary_manager_dictionary_value_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ListDictionaryValueReply_DictionaryValue) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListDictionaryValueReply_DictionaryValue) GetDictionaryId() uint32 {
	if x != nil {
		return x.DictionaryId
	}
	return 0
}

func (x *ListDictionaryValueReply_DictionaryValue) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ListDictionaryValueReply_DictionaryValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ListDictionaryValueReply_DictionaryValue) GetStatus() bool {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return false
}

func (x *ListDictionaryValueReply_DictionaryValue) GetWeight() int32 {
	if x != nil && x.Weight != nil {
		return *x.Weight
	}
	return 0
}

func (x *ListDictionaryValueReply_DictionaryValue) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *ListDictionaryValueReply_DictionaryValue) GetExtra() string {
	if x != nil && x.Extra != nil {
		return *x.Extra
	}
	return ""
}

func (x *ListDictionaryValueReply_DictionaryValue) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ListDictionaryValueReply_DictionaryValue) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ListDictionaryValueReply_DictionaryValue) GetUpdatedAt() uint32 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_api_manager_dictionary_manager_dictionary_value_proto protoreflect.FileDescriptor

var file_api_manager_dictionary_manager_dictionary_value_proto_rawDesc = []byte{
	0x0a, 0x35, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x64, 0x69,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x5f, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x21, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x64, 0x69, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x26, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x42, 0x0a, 0xfa, 0x42, 0x07, 0x92, 0x01, 0x04, 0x08, 0x01, 0x18, 0x01, 0x52,
	0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x22, 0x8a, 0x04, 0x0a, 0x18, 0x47, 0x65,
	0x74, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x59, 0x0a, 0x04, 0x64, 0x69, 0x63, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x45, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x64, 0x69, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x2e, 0x44, 0x69, 0x63, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x64, 0x69, 0x63,
	0x74, 0x1a, 0x96, 0x02, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x5a, 0x0a, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x46, 0x2e, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e,
	0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0xb0, 0x01, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x17, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x88, 0x01, 0x01,
	0x12, 0x25, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x78, 0x74, 0x72, 0x61, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x7a, 0x0a, 0x09, 0x44, 0x69,
	0x63, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x57, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x41, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x64,
	0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x8d, 0x03, 0x0a, 0x1a, 0x4c, 0x69, 0x73, 0x74, 0x44,
	0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x01, 0x52, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x12, 0x25, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x2a, 0x04, 0x18, 0x32, 0x28, 0x01, 0x52,
	0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x10, 0xfa, 0x42, 0x0d, 0x72, 0x0b, 0x52,
	0x03, 0x61, 0x73, 0x63, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x48, 0x00, 0x52, 0x05, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x3c, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x1d, 0xfa, 0x42, 0x1a, 0x72, 0x18, 0x52, 0x02,
	0x69, 0x64, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x52, 0x06,
	0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x48, 0x01, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42,
	0x79, 0x88, 0x01, 0x01, 0x12, 0x27, 0x0a, 0x0c, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x72, 0x79, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x02, 0x52, 0x0c, 0x64, 0x69,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a,
	0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x05,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x48, 0x04, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x08, 0x48, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x88, 0x01, 0x01,
	0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x64, 0x69, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x64, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x8f, 0x04, 0x0a, 0x18, 0x4c, 0x69, 0x73, 0x74, 0x44,
	0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x5f, 0x0a, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x4b, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x64, 0x69,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x2e, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0xfb, 0x02, 0x0a, 0x0f, 0x44,
	0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22,
	0x0a, 0x0c, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1b,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x77,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x06, 0x77,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x88, 0x01,
	0x01, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x03, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x04, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x88, 0x01, 0x01, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x42,
	0x09, 0x0a, 0x07, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x77,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x42, 0x08,
	0x0a, 0x06, 0x5f, 0x65, 0x78, 0x74, 0x72, 0x61, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xd7, 0x02, 0x0a, 0x1c, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x0c, 0x64, 0x69, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42,
	0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x01, 0x52, 0x0c, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x72, 0x79, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x05,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x1d, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x1b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x88, 0x01,
	0x01, 0x12, 0x1b, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x48, 0x01, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x88, 0x01, 0x01, 0x12, 0x17,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x88,
	0x01, 0x01, 0x12, 0x25, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x48, 0x04, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x42,
	0x07, 0x0a, 0x05, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x78, 0x74,
	0x72, 0x61, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x2c, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x69, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64,
	0x22, 0xc8, 0x02, 0x0a, 0x1c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa,
	0x42, 0x04, 0x2a, 0x02, 0x28, 0x01, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2b, 0x0a, 0x0c, 0x64, 0x69,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x01, 0x52, 0x0c, 0x64, 0x69, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x72, 0x79, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52,
	0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x1d, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1b, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x88,
	0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x01, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x65,
	0x78, 0x74, 0x72, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x05, 0x65, 0x78,
	0x74, 0x72, 0x61, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a,
	0x07, 0x5f, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x78, 0x74, 0x72, 0x61, 0x42, 0x0e, 0x0a, 0x0c, 0x5f,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x1c, 0x0a, 0x1a, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x55, 0x0a, 0x22, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x07, 0xfa, 0x42, 0x04,
	0x2a, 0x02, 0x28, 0x01, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x22, 0x0a, 0x20, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x37, 0x0a, 0x1c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x69,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x42, 0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x28, 0x01, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1c, 0x0a,
	0x1a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72,
	0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x3c, 0x0a, 0x21, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x2e, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x76, 0x31,
	0x42, 0x0c, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x56, 0x31, 0x50, 0x01,
	0x5a, 0x07, 0x2e, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_manager_dictionary_manager_dictionary_value_proto_rawDescOnce sync.Once
	file_api_manager_dictionary_manager_dictionary_value_proto_rawDescData = file_api_manager_dictionary_manager_dictionary_value_proto_rawDesc
)

func file_api_manager_dictionary_manager_dictionary_value_proto_rawDescGZIP() []byte {
	file_api_manager_dictionary_manager_dictionary_value_proto_rawDescOnce.Do(func() {
		file_api_manager_dictionary_manager_dictionary_value_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_manager_dictionary_manager_dictionary_value_proto_rawDescData)
	})
	return file_api_manager_dictionary_manager_dictionary_value_proto_rawDescData
}

var file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_manager_dictionary_manager_dictionary_value_proto_goTypes = []interface{}{
	(*GetDictionaryValuesRequest)(nil),               // 0: manager.api.manager.dictionary.v1.GetDictionaryValuesRequest
	(*GetDictionaryValuesReply)(nil),                 // 1: manager.api.manager.dictionary.v1.GetDictionaryValuesReply
	(*ListDictionaryValueRequest)(nil),               // 2: manager.api.manager.dictionary.v1.ListDictionaryValueRequest
	(*ListDictionaryValueReply)(nil),                 // 3: manager.api.manager.dictionary.v1.ListDictionaryValueReply
	(*CreateDictionaryValueRequest)(nil),             // 4: manager.api.manager.dictionary.v1.CreateDictionaryValueRequest
	(*CreateDictionaryValueReply)(nil),               // 5: manager.api.manager.dictionary.v1.CreateDictionaryValueReply
	(*UpdateDictionaryValueRequest)(nil),             // 6: manager.api.manager.dictionary.v1.UpdateDictionaryValueRequest
	(*UpdateDictionaryValueReply)(nil),               // 7: manager.api.manager.dictionary.v1.UpdateDictionaryValueReply
	(*UpdateDictionaryValueStatusRequest)(nil),       // 8: manager.api.manager.dictionary.v1.UpdateDictionaryValueStatusRequest
	(*UpdateDictionaryValueStatusReply)(nil),         // 9: manager.api.manager.dictionary.v1.UpdateDictionaryValueStatusReply
	(*DeleteDictionaryValueRequest)(nil),             // 10: manager.api.manager.dictionary.v1.DeleteDictionaryValueRequest
	(*DeleteDictionaryValueReply)(nil),               // 11: manager.api.manager.dictionary.v1.DeleteDictionaryValueReply
	(*GetDictionaryValuesReply_Value)(nil),           // 12: manager.api.manager.dictionary.v1.GetDictionaryValuesReply.Value
	nil,                                              // 13: manager.api.manager.dictionary.v1.GetDictionaryValuesReply.DictEntry
	(*GetDictionaryValuesReply_Value_Item)(nil),      // 14: manager.api.manager.dictionary.v1.GetDictionaryValuesReply.Value.Item
	(*ListDictionaryValueReply_DictionaryValue)(nil), // 15: manager.api.manager.dictionary.v1.ListDictionaryValueReply.DictionaryValue
}
var file_api_manager_dictionary_manager_dictionary_value_proto_depIdxs = []int32{
	13, // 0: manager.api.manager.dictionary.v1.GetDictionaryValuesReply.dict:type_name -> manager.api.manager.dictionary.v1.GetDictionaryValuesReply.DictEntry
	15, // 1: manager.api.manager.dictionary.v1.ListDictionaryValueReply.list:type_name -> manager.api.manager.dictionary.v1.ListDictionaryValueReply.DictionaryValue
	14, // 2: manager.api.manager.dictionary.v1.GetDictionaryValuesReply.Value.list:type_name -> manager.api.manager.dictionary.v1.GetDictionaryValuesReply.Value.Item
	12, // 3: manager.api.manager.dictionary.v1.GetDictionaryValuesReply.DictEntry.value:type_name -> manager.api.manager.dictionary.v1.GetDictionaryValuesReply.Value
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_manager_dictionary_manager_dictionary_value_proto_init() }
func file_api_manager_dictionary_manager_dictionary_value_proto_init() {
	if File_api_manager_dictionary_manager_dictionary_value_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDictionaryValuesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDictionaryValuesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDictionaryValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDictionaryValueReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDictionaryValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDictionaryValueReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDictionaryValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDictionaryValueReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDictionaryValueStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDictionaryValueStatusReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDictionaryValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDictionaryValueReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDictionaryValuesReply_Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDictionaryValuesReply_Value_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDictionaryValueReply_DictionaryValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[6].OneofWrappers = []interface{}{}
	file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[14].OneofWrappers = []interface{}{}
	file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes[15].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_manager_dictionary_manager_dictionary_value_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_manager_dictionary_manager_dictionary_value_proto_goTypes,
		DependencyIndexes: file_api_manager_dictionary_manager_dictionary_value_proto_depIdxs,
		MessageInfos:      file_api_manager_dictionary_manager_dictionary_value_proto_msgTypes,
	}.Build()
	File_api_manager_dictionary_manager_dictionary_value_proto = out.File
	file_api_manager_dictionary_manager_dictionary_value_proto_rawDesc = nil
	file_api_manager_dictionary_manager_dictionary_value_proto_goTypes = nil
	file_api_manager_dictionary_manager_dictionary_value_proto_depIdxs = nil
}
