// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/manager/system/manager_system.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetSystemSettingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSystemSettingRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSystemSettingRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSystemSettingRequestMultiError, or nil if none found.
func (m *GetSystemSettingRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSystemSettingRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetSystemSettingRequestMultiError(errors)
	}

	return nil
}

// GetSystemSettingRequestMultiError is an error wrapping multiple validation
// errors returned by GetSystemSettingRequest.ValidateAll() if the designated
// constraints aren't met.
type GetSystemSettingRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSystemSettingRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSystemSettingRequestMultiError) AllErrors() []error { return m }

// GetSystemSettingRequestValidationError is the validation error returned by
// GetSystemSettingRequest.Validate if the designated constraints aren't met.
type GetSystemSettingRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSystemSettingRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSystemSettingRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSystemSettingRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSystemSettingRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSystemSettingRequestValidationError) ErrorName() string {
	return "GetSystemSettingRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetSystemSettingRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSystemSettingRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSystemSettingRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSystemSettingRequestValidationError{}

// Validate checks the field values on DictionaryValue with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DictionaryValue) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DictionaryValue with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DictionaryValueMultiError, or nil if none found.
func (m *DictionaryValue) ValidateAll() error {
	return m.validate(true)
}

func (m *DictionaryValue) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Label

	// no validation rules for Value

	if m.Type != nil {
		// no validation rules for Type
	}

	if m.Extra != nil {
		// no validation rules for Extra
	}

	if len(errors) > 0 {
		return DictionaryValueMultiError(errors)
	}

	return nil
}

// DictionaryValueMultiError is an error wrapping multiple validation errors
// returned by DictionaryValue.ValidateAll() if the designated constraints
// aren't met.
type DictionaryValueMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DictionaryValueMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DictionaryValueMultiError) AllErrors() []error { return m }

// DictionaryValueValidationError is the validation error returned by
// DictionaryValue.Validate if the designated constraints aren't met.
type DictionaryValueValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DictionaryValueValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DictionaryValueValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DictionaryValueValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DictionaryValueValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DictionaryValueValidationError) ErrorName() string { return "DictionaryValueValidationError" }

// Error satisfies the builtin error interface
func (e DictionaryValueValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDictionaryValue.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DictionaryValueValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DictionaryValueValidationError{}

// Validate checks the field values on GetSystemSettingReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSystemSettingReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSystemSettingReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSystemSettingReplyMultiError, or nil if none found.
func (m *GetSystemSettingReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSystemSettingReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Debug

	// no validation rules for Title

	// no validation rules for Desc

	// no validation rules for Copyright

	// no validation rules for Logo

	// no validation rules for ChangePasswordType

	// no validation rules for Watermark

	{
		sorted_keys := make([]string, len(m.GetDictionaries()))
		i := 0
		for key := range m.GetDictionaries() {
			sorted_keys[i] = key
			i++
		}
		sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
		for _, key := range sorted_keys {
			val := m.GetDictionaries()[key]
			_ = val

			// no validation rules for Dictionaries[key]

			if all {
				switch v := interface{}(val).(type) {
				case interface{ ValidateAll() error }:
					if err := v.ValidateAll(); err != nil {
						errors = append(errors, GetSystemSettingReplyValidationError{
							field:  fmt.Sprintf("Dictionaries[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				case interface{ Validate() error }:
					if err := v.Validate(); err != nil {
						errors = append(errors, GetSystemSettingReplyValidationError{
							field:  fmt.Sprintf("Dictionaries[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				}
			} else if v, ok := interface{}(val).(interface{ Validate() error }); ok {
				if err := v.Validate(); err != nil {
					return GetSystemSettingReplyValidationError{
						field:  fmt.Sprintf("Dictionaries[%v]", key),
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		}
	}

	if len(errors) > 0 {
		return GetSystemSettingReplyMultiError(errors)
	}

	return nil
}

// GetSystemSettingReplyMultiError is an error wrapping multiple validation
// errors returned by GetSystemSettingReply.ValidateAll() if the designated
// constraints aren't met.
type GetSystemSettingReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSystemSettingReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSystemSettingReplyMultiError) AllErrors() []error { return m }

// GetSystemSettingReplyValidationError is the validation error returned by
// GetSystemSettingReply.Validate if the designated constraints aren't met.
type GetSystemSettingReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSystemSettingReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSystemSettingReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSystemSettingReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSystemSettingReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSystemSettingReplyValidationError) ErrorName() string {
	return "GetSystemSettingReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetSystemSettingReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSystemSettingReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSystemSettingReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSystemSettingReplyValidationError{}

// Validate checks the field values on
// GetSystemSettingReply_DictionaryValueList with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetSystemSettingReply_DictionaryValueList) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// GetSystemSettingReply_DictionaryValueList with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in
// GetSystemSettingReply_DictionaryValueListMultiError, or nil if none found.
func (m *GetSystemSettingReply_DictionaryValueList) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSystemSettingReply_DictionaryValueList) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetSystemSettingReply_DictionaryValueListValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetSystemSettingReply_DictionaryValueListValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetSystemSettingReply_DictionaryValueListValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetSystemSettingReply_DictionaryValueListMultiError(errors)
	}

	return nil
}

// GetSystemSettingReply_DictionaryValueListMultiError is an error wrapping
// multiple validation errors returned by
// GetSystemSettingReply_DictionaryValueList.ValidateAll() if the designated
// constraints aren't met.
type GetSystemSettingReply_DictionaryValueListMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSystemSettingReply_DictionaryValueListMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSystemSettingReply_DictionaryValueListMultiError) AllErrors() []error { return m }

// GetSystemSettingReply_DictionaryValueListValidationError is the validation
// error returned by GetSystemSettingReply_DictionaryValueList.Validate if the
// designated constraints aren't met.
type GetSystemSettingReply_DictionaryValueListValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSystemSettingReply_DictionaryValueListValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSystemSettingReply_DictionaryValueListValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSystemSettingReply_DictionaryValueListValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSystemSettingReply_DictionaryValueListValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSystemSettingReply_DictionaryValueListValidationError) ErrorName() string {
	return "GetSystemSettingReply_DictionaryValueListValidationError"
}

// Error satisfies the builtin error interface
func (e GetSystemSettingReply_DictionaryValueListValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSystemSettingReply_DictionaryValueList.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSystemSettingReply_DictionaryValueListValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSystemSettingReply_DictionaryValueListValidationError{}
